//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeDevPnP.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeDevPnP.Core.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting authentication context for &apos;{0}&apos;.
        /// </summary>
        internal static string AuthenticationManager_GetContext {
            get {
                return ResourceManager.GetString("AuthenticationManager_GetContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant user &apos;{0}&apos;.
        /// </summary>
        internal static string AuthenticationManager_TenantUser {
            get {
                return ResourceManager.GetString("AuthenticationManager_TenantUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine lease for appOnlyAccessToken..
        /// </summary>
        internal static string AuthenticationManger_ProblemDeterminingTokenLease {
            get {
                return ResourceManager.GetString("AuthenticationManger_ProblemDeterminingTokenLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding theme option &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string BrandingExtension_AddThemeOption {
            get {
                return ResourceManager.GetString("BrandingExtension_AddThemeOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying masterpage &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string BrandingExtension_DeployMasterPage {
            get {
                return ResourceManager.GetString("BrandingExtension_DeployMasterPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying page layout &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string BrandingExtension_DeployPageLayout {
            get {
                return ResourceManager.GetString("BrandingExtension_DeployPageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying theme &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        internal static string BrandingExtension_DeployTheme {
            get {
                return ResourceManager.GetString("BrandingExtension_DeployTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploying file &apos;{0}&apos; to &apos;{1}&apos; folder &apos;{2}&apos;..
        /// </summary>
        internal static string BrandingExtension_DeployThemeFile {
            get {
                return ResourceManager.GetString("BrandingExtension_DeployThemeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting custom master URL &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string BrandingExtension_SetCustomMasterUrl {
            get {
                return ResourceManager.GetString("BrandingExtension_SetCustomMasterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting master URL &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string BrandingExtension_SetMasterUrl {
            get {
                return ResourceManager.GetString("BrandingExtension_SetMasterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting theme &apos;{0}&apos; for &apos;{1}&apos;.
        /// </summary>
        internal static string BrandingExtension_SetTheme {
            get {
                return ResourceManager.GetString("BrandingExtension_SetTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme &apos;{0}&apos; not found..
        /// </summary>
        internal static string BrandingExtension_ThemeMissing {
            get {
                return ResourceManager.GetString("BrandingExtension_ThemeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme &apos;{0}&apos; already exists (and was not overwritten). No changes made..
        /// </summary>
        internal static string BrandingExtension_ThemeNotOverwritten {
            get {
                return ResourceManager.GetString("BrandingExtension_ThemeNotOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed argument is a zero-length string or contains only whitespace..
        /// </summary>
        internal static string Exception_Message_EmptyString_Arg {
            get {
                return ResourceManager.GetString("Exception_Message_EmptyString_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating feature {0} in site collection..
        /// </summary>
        internal static string FeatureExtensions_ActivateSiteCollectionFeature {
            get {
                return ResourceManager.GetString("FeatureExtensions_ActivateSiteCollectionFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating feature {0} in web..
        /// </summary>
        internal static string FeatureExtensions_ActivateWebFeature {
            get {
                return ResourceManager.GetString("FeatureExtensions_ActivateWebFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating feature {0} in site collection..
        /// </summary>
        internal static string FeatureExtensions_DeactivateSiteCollectionFeature {
            get {
                return ResourceManager.GetString("FeatureExtensions_DeactivateSiteCollectionFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating feature {0} in web..
        /// </summary>
        internal static string FeatureExtensions_DeactivateWebFeature {
            get {
                return ResourceManager.GetString("FeatureExtensions_DeactivateWebFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with activation for feature id {0}..
        /// </summary>
        internal static string FeatureExtensions_FeatureActivationProblem {
            get {
                return ResourceManager.GetString("FeatureExtensions_FeatureActivationProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding field ({0}) to content type ({1})..
        /// </summary>
        internal static string FieldAndContentTypeExtensions_AddField0ToContentType1 {
            get {
                return ResourceManager.GetString("FieldAndContentTypeExtensions_AddField0ToContentType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type &apos;{0}&apos; ({1}) already exists; no changes made..
        /// </summary>
        internal static string FieldAndContentTypeExtensions_ContentType01AlreadyExists {
            get {
                return ResourceManager.GetString("FieldAndContentTypeExtensions_ContentType01AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating content type &apos;{0}&apos; ({1})..
        /// </summary>
        internal static string FieldAndContentTypeExtensions_CreateContentType01 {
            get {
                return ResourceManager.GetString("FieldAndContentTypeExtensions_CreateContentType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating document set &apos;{0}&apos;..
        /// </summary>
        internal static string FieldAndContentTypeExtensions_CreateDocumentSet {
            get {
                return ResourceManager.GetString("FieldAndContentTypeExtensions_CreateDocumentSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating field &apos;{0}&apos; ({1})..
        /// </summary>
        internal static string FieldAndContentTypeExtensions_CreateField01 {
            get {
                return ResourceManager.GetString("FieldAndContentTypeExtensions_CreateField01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Field as XML: {0}.
        /// </summary>
        internal static string FieldAndContentTypeExtensions_CreateFieldBase {
            get {
                return ResourceManager.GetString("FieldAndContentTypeExtensions_CreateFieldBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; ({1}) already exists; no changes made..
        /// </summary>
        internal static string FieldAndContentTypeExtensions_Field01AlreadyExists {
            get {
                return ResourceManager.GetString("FieldAndContentTypeExtensions_Field01AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder does not exist in the web. Web: {0}, Folder: {1}.
        /// </summary>
        internal static string FileFolderExtensions_FolderMissing {
            get {
                return ResourceManager.GetString("FileFolderExtensions_FolderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target library does not exist in the web. Web: {0}, List: {1}.
        /// </summary>
        internal static string FileFolderExtensions_LibraryMissing {
            get {
                return ResourceManager.GetString("FileFolderExtensions_LibraryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading file &apos;{0}&apos; to folder &apos;{1}&apos;..
        /// </summary>
        internal static string FileFolderExtensions_UploadFile {
            get {
                return ResourceManager.GetString("FileFolderExtensions_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}; EXCEPTION: {{{1}}}.
        /// </summary>
        internal static string LoggingUtility_MessageWithException {
            get {
                return ResourceManager.GetString("LoggingUtility_MessageWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail message could not be sent. SMTP exception attempting to send..
        /// </summary>
        internal static string MailUtility_SendException {
            get {
                return ResourceManager.GetString("MailUtility_SendException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail message could not be sent. Exception attempting to send email, rethrowing. Exception: {0}.
        /// </summary>
        internal static string MailUtility_SendExceptionRethrow0 {
            get {
                return ResourceManager.GetString("MailUtility_SendExceptionRethrow0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail message could not be sent. Send completed with error..
        /// </summary>
        internal static string MailUtility_SendFailed {
            get {
                return ResourceManager.GetString("MailUtility_SendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail message was canceled..
        /// </summary>
        internal static string MailUtility_SendMailCancelled {
            get {
                return ResourceManager.GetString("MailUtility_SendMailCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating term group &apos;{0}&apos; in term store &apos;{1}&apos;..
        /// </summary>
        internal static string TaxonomyExtension_CreateTermGroup0InStore1 {
            get {
                return ResourceManager.GetString("TaxonomyExtension_CreateTermGroup0InStore1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating term set &apos;{0}&apos; in term group &apos;{1}&apos;..
        /// </summary>
        internal static string TaxonomyExtension_CreateTermSet0InGroup1 {
            get {
                return ResourceManager.GetString("TaxonomyExtension_CreateTermSet0InGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting description for term group &apos;{0}&apos; ({1})..
        /// </summary>
        internal static string TaxonomyExtension_ExceptionUpdateDescriptionGroup01 {
            get {
                return ResourceManager.GetString("TaxonomyExtension_ExceptionUpdateDescriptionGroup01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting description for term set &apos;{0}&apos; ({1})..
        /// </summary>
        internal static string TaxonomyExtension_ExceptionUpdateDescriptionSet01 {
            get {
                return ResourceManager.GetString("TaxonomyExtension_ExceptionUpdateDescriptionSet01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term group &apos;{0}&apos; ID ({1}) does not match specified ID ({2})..
        /// </summary>
        internal static string TaxonomyExtension_TermGroup0Id1DoesNotMatchSpecifiedId2 {
            get {
                return ResourceManager.GetString("TaxonomyExtension_TermGroup0Id1DoesNotMatchSpecifiedId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term set &apos;{0}&apos; ID ({1}) does not match specified ID ({2})..
        /// </summary>
        internal static string TaxonomyExtension_TermSet0Id1DoesNotMatchSpecifiedId2 {
            get {
                return ResourceManager.GetString("TaxonomyExtension_TermSet0Id1DoesNotMatchSpecifiedId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientContext gets closed after action is completed. Calling ExecuteQuery again returns an error. Verify that you have an open ClientContext object..
        /// </summary>
        internal static string TenantExtensions_ClosedContextWarning {
            get {
                return ResourceManager.GetString("TenantExtensions_ClosedContextWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine if site exists in tenant..
        /// </summary>
        internal static string TenantExtensions_UnknownExceptionAccessingSite {
            get {
                return ResourceManager.GetString("TenantExtensions_UnknownExceptionAccessingSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating web &apos;{0}&apos; with template &apos;{1}&apos;..
        /// </summary>
        internal static string WebExtensions_CreateWeb {
            get {
                return ResourceManager.GetString("WebExtensions_CreateWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting web &apos;{0}&apos;..
        /// </summary>
        internal static string WebExtensions_DeleteWeb {
            get {
                return ResourceManager.GetString("WebExtensions_DeleteWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing sandbox solution &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string WebExtensions_InstallSolution {
            get {
                return ResourceManager.GetString("WebExtensions_InstallSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing app &apos;{0}&apos; instance {1}..
        /// </summary>
        internal static string WebExtensions_RemoveAppInstance {
            get {
                return ResourceManager.GetString("WebExtensions_RemoveAppInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site search error..
        /// </summary>
        internal static string WebExtensions_SiteSearchUnhandledException {
            get {
                return ResourceManager.GetString("WebExtensions_SiteSearchUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing sandbox solution &apos;{0}&apos;..
        /// </summary>
        internal static string WebExtensions_UninstallSolution {
            get {
                return ResourceManager.GetString("WebExtensions_UninstallSolution", resourceCulture);
            }
        }
    }
}
