//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perficient.Provisioning.VSTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Perficient.Provisioning.VSTools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pnpsitetemplate.xml.
        /// </summary>
        internal static string DefaultFileNamePnPTemplate {
            get {
                return ResourceManager.GetString("DefaultFileNamePnPTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;pnp:Provisioning xmlns:pnp=&quot;http://schemas.dev.office.com/PnP/2015/12/ProvisioningSchema&quot;&gt;
        ///  &lt;pnp:Templates ID=&quot;CONTAINER-DefaultTemplate&quot;&gt;
        ///    &lt;pnp:ProvisioningTemplate ID=&quot;DefaultTemplate&quot; Version=&quot;1&quot;&gt;
        ///    &lt;/pnp:ProvisioningTemplate&gt;
        ///  &lt;/pnp:Templates&gt;
        ///&lt;/pnp:Provisioning&gt;.
        /// </summary>
        internal static string defaultPnPTemplate {
            get {
                return ResourceManager.GetString("defaultPnPTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPResources.
        /// </summary>
        internal static string DefaultResourcesRelativePath {
            get {
                return ResourceManager.GetString("DefaultResourcesRelativePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable PnP Provisioning Tools.
        /// </summary>
        internal static string DisablePnPToolsText {
            get {
                return ResourceManager.GetString("DisablePnPToolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit PnP Provisioning Tools Conncection.
        /// </summary>
        internal static string EditConnPnPToolsText {
            get {
                return ResourceManager.GetString("EditConnPnPToolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable PnP Provisioning Tools.
        /// </summary>
        internal static string EnablePnPToolsText {
            get {
                return ResourceManager.GetString("EnablePnPToolsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProvisioningTemplateTools.config.
        /// </summary>
        internal static string FileNameProvisioningTemplate {
            get {
                return ResourceManager.GetString("FileNameProvisioningTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProvisioningTemplateTools.config.user.
        /// </summary>
        internal static string FileNameProvisioningUserCreds {
            get {
                return ResourceManager.GetString("FileNameProvisioningUserCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisioning Configuration.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
    }
}
