//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeDevPnP.SPOnline.Commands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeDevPnP.SPOnline.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso SPOnline PowerShell Library.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command not executed due to healthscore value of {0}.
        /// </summary>
        internal static string CommandNotExecutedDueToHealthscoreValueOf0 {
            get {
                return ResourceManager.GetString("CommandNotExecutedDueToHealthscoreValueOf0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contoso SPOnline PowerShell Library ({0}).
        /// </summary>
        internal static string ContosoSPOnlinePowerShellLibrary0 {
            get {
                return ResourceManager.GetString("ContosoSPOnlinePowerShellLibrary0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current site is not a tenant administration site.
        /// </summary>
        internal static string CurrentSiteIsNoTenantAdminSite {
            get {
                return ResourceManager.GetString("CurrentSiteIsNoTenantAdminSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &apos;{0}&apos;?.
        /// </summary>
        internal static string Delete0 {
            get {
                return ResourceManager.GetString("Delete0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete field &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteField0 {
            get {
                return ResourceManager.GetString("DeleteField0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your credentials.
        /// </summary>
        internal static string EnterYourCredentials {
            get {
                return ResourceManager.GetString("EnterYourCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} exists, overwrite?.
        /// </summary>
        internal static string File0ExistsOverwrite {
            get {
                return ResourceManager.GetString("File0ExistsOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health score not sufficient.
        /// </summary>
        internal static string HealthScoreNotSufficient {
            get {
                return ResourceManager.GetString("HealthScoreNotSufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List not found.
        /// </summary>
        internal static string ListNotFound {
            get {
                return ResourceManager.GetString("ListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 87294c72-f260-42f3-a41b-981a2ffce37a.
        /// </summary>
        internal static string MDSFeatureGuid {
            get {
                return ResourceManager.GetString("MDSFeatureGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection, please connect first with Connect-SPOnline.
        /// </summary>
        internal static string NoConnection {
            get {
                return ResourceManager.GetString("NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to disconnect.
        /// </summary>
        internal static string NoConnectionToDisconnect {
            get {
                return ResourceManager.GetString("NoConnectionToDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No context present. Connect first with Connect-SPOnline.
        /// </summary>
        internal static string NoContextPresent {
            get {
                return ResourceManager.GetString("NoContextPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove content type?.
        /// </summary>
        internal static string RemoveContentType {
            get {
                return ResourceManager.GetString("RemoveContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove custom action?.
        /// </summary>
        internal static string RemoveCustomAction {
            get {
                return ResourceManager.GetString("RemoveCustomAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove event receiver?.
        /// </summary>
        internal static string RemoveEventReceiver {
            get {
                return ResourceManager.GetString("RemoveEventReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove key and value from property bag?.
        /// </summary>
        internal static string RemoveKeyAndValueFromPropertyBag {
            get {
                return ResourceManager.GetString("RemoveKeyAndValueFromPropertyBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove list?.
        /// </summary>
        internal static string RemoveList {
            get {
                return ResourceManager.GetString("RemoveList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove propertybag value.
        /// </summary>
        internal static string RemovePropertyBagValue {
            get {
                return ResourceManager.GetString("RemovePropertyBagValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove site collection &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveSiteCollection0 {
            get {
                return ResourceManager.GetString("RemoveSiteCollection0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the {0} key and its value from the property bag?.
        /// </summary>
        internal static string RemoveThe0KeyAndItsValueFromThePropertyBag {
            get {
                return ResourceManager.GetString("RemoveThe0KeyAndItsValueFromThePropertyBag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove view &apos;{0}&apos;?.
        /// </summary>
        internal static string RemoveView0 {
            get {
                return ResourceManager.GetString("RemoveView0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry {0}: Server not healthy, waiting {1} seconds (Server Health Score: {2}).
        /// </summary>
        internal static string Retry0ServerNotHealthyWaiting1seconds {
            get {
                return ResourceManager.GetString("Retry0ServerNotHealthyWaiting1seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web &apos;{0}&apos; created at {1}.
        /// </summary>
        internal static string Web0CreatedAt1 {
            get {
                return ResourceManager.GetString("Web0CreatedAt1", resourceCulture);
            }
        }
    }
}
