//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeDevPnP.SPOnline.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeDevPnP.SPOnline.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE3A1339-61F5-4f8f-81A7-ABD2DA956A7D.
        /// </summary>
        internal static string AppSideLoadingFeatureGuid {
            get {
                return ResourceManager.GetString("AppSideLoadingFeatureGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_vti_bin/contoso.services.sitemanager/sitemanager.svc.
        /// </summary>
        internal static string ContosoServicesSiteManagerEndPointAddress {
            get {
                return ResourceManager.GetString("ContosoServicesSiteManagerEndPointAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding file: {0}.
        /// </summary>
        internal static string ErrorAddingFile0 {
            get {
                return ResourceManager.GetString("ErrorAddingFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error approving file: {0}.
        /// </summary>
        internal static string ErrorApprovingFile0 {
            get {
                return ResourceManager.GetString("ErrorApprovingFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking in file: {0}.
        /// </summary>
        internal static string ErrorCheckingInFile0 {
            get {
                return ResourceManager.GetString("ErrorCheckingInFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking out file: {0}.
        /// </summary>
        internal static string ErrorCheckingOutFile0 {
            get {
                return ResourceManager.GetString("ErrorCheckingOutFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error publishing file: {0}.
        /// </summary>
        internal static string ErrorPublishingFile0 {
            get {
                return ResourceManager.GetString("ErrorPublishingFile0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No webparts on this page.
        /// </summary>
        internal static string NoWebpartsOnThisPage {
            get {
                return ResourceManager.GetString("NoWebpartsOnThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation has timed out.
        /// </summary>
        internal static string OperationTimedOut {
            get {
                return ResourceManager.GetString("OperationTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL should include filename.
        /// </summary>
        internal static string URLShouldIncludeFileName {
            get {
                return ResourceManager.GetString("URLShouldIncludeFileName", resourceCulture);
            }
        }
    }
}
