//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contoso.Provisioning.Hybrid.Web.SharePointProvisioning {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SharePointProvisioning.ISharePointProvisioningService")]
    public interface ISharePointProvisioningService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharePointProvisioningService/ProvisionSiteCollection", ReplyAction="http://tempuri.org/ISharePointProvisioningService/ProvisionSiteCollectionResponse" +
            "")]
        bool ProvisionSiteCollection(Contoso.Provisioning.Hybrid.Contract.SharePointProvisioningData sharePointProvisioningData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISharePointProvisioningService/ProvisionSiteCollection", ReplyAction="http://tempuri.org/ISharePointProvisioningService/ProvisionSiteCollectionResponse" +
            "")]
        System.Threading.Tasks.Task<bool> ProvisionSiteCollectionAsync(Contoso.Provisioning.Hybrid.Contract.SharePointProvisioningData sharePointProvisioningData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISharePointProvisioningServiceChannel : Contoso.Provisioning.Hybrid.Web.SharePointProvisioning.ISharePointProvisioningService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SharePointProvisioningServiceClient : System.ServiceModel.ClientBase<Contoso.Provisioning.Hybrid.Web.SharePointProvisioning.ISharePointProvisioningService>, Contoso.Provisioning.Hybrid.Web.SharePointProvisioning.ISharePointProvisioningService {
        
        public SharePointProvisioningServiceClient() {
        }
        
        public SharePointProvisioningServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SharePointProvisioningServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharePointProvisioningServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SharePointProvisioningServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ProvisionSiteCollection(Contoso.Provisioning.Hybrid.Contract.SharePointProvisioningData sharePointProvisioningData) {
            return base.Channel.ProvisionSiteCollection(sharePointProvisioningData);
        }
        
        public System.Threading.Tasks.Task<bool> ProvisionSiteCollectionAsync(Contoso.Provisioning.Hybrid.Contract.SharePointProvisioningData sharePointProvisioningData) {
            return base.Channel.ProvisionSiteCollectionAsync(sharePointProvisioningData);
        }
    }
}
