//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Provisioning.Framework.Extensions.NavigationProvisionSchema {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dev.office.com/PnP/2015/05/ProvisioningSchema/Extentions/Navigatio" +
        "n")]
    [System.Xml.Serialization.XmlRootAttribute("Navigations", Namespace="http://schemas.dev.office.com/PnP/2015/05/ProvisioningSchema/Extentions/Navigatio" +
        "n", IsNullable=false)]
    public partial class NavigationList {
        
        private NavigationConfiguration[] navigationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Navigation")]
        public NavigationConfiguration[] Navigation {
            get {
                return this.navigationField;
            }
            set {
                this.navigationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dev.office.com/PnP/2015/05/ProvisioningSchema/Extentions/Navigatio" +
        "n")]
    public partial class NavigationConfiguration {
        
        private NavigationNode[] itemsField;
        
        private int rootNodeIdField;
        
        private bool rootNodeIdFieldSpecified;
        
        private string siteMapProviderField;
        
        private NavigationType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NavigationNode")]
        public NavigationNode[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int RootNodeId {
            get {
                return this.rootNodeIdField;
            }
            set {
                this.rootNodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RootNodeIdSpecified {
            get {
                return this.rootNodeIdFieldSpecified;
            }
            set {
                this.rootNodeIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SiteMapProvider {
            get {
                return this.siteMapProviderField;
            }
            set {
                this.siteMapProviderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public NavigationType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dev.office.com/PnP/2015/05/ProvisioningSchema/Extentions/Navigatio" +
        "n")]
    public partial class NavigationNode {
        
        private string titleField;
        
        private string urlField;
        
        private bool isExternalField;
        
        private bool isExternalFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsExternal {
            get {
                return this.isExternalField;
            }
            set {
                this.isExternalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsExternalSpecified {
            get {
                return this.isExternalFieldSpecified;
            }
            set {
                this.isExternalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dev.office.com/PnP/2015/05/ProvisioningSchema/Extentions/Navigatio" +
        "n")]
    public enum NavigationType {
        
        /// <remarks/>
        Structural,
        
        /// <remarks/>
        Taxonomy,
    }
}
