// This file is generated by Visual Studio to enable IntelliSense for the Office JavaScript Object Model.

var Office = new function() {
    this._appContext = 8;
    this._showAll = false;
    this._setContext = {
        MAILBOX: "1.3"
    };
}

// 1 Excel appContext = 001
// 2 Word appContext = 010
// 3 Word + Excel appContext = 011
// 4 Project appContext = 100
// 5 Project + Excel appContext = 101
// 6 Project + Word appContext = 110
// 7 Project + Word + Excel appContext = 111
// 8 Outlook read-form appContext = 1000
// 16 PowerPoint appContext = 10000
// 17 PowerPoint + Excel appContext = 10001
// 18 PowerPoint + Word appContext = 10010
// 19 PowerPoint + Word + Excel appContext = 10011
// 20 PowerPoint + Project appContext = 10100
// 21 PowerPoint + Project + Excel appContext = 10101
// 22 PowerPoint + Project + Word appContext = 10110
// 23 PowerPoint + Project + Word + Excel appContext = 10111
// 32 Outlook compose-form appContext = 100000
// 40 Outlook read-form + Outlook compose form appContext = 101000
// 64 Access appContext = 1000000
// 65 Access + Excel appContext = 1000001
// 66 Access + Word appContext = 1000010
// 67 Access + Word + Excel appContext = 1000011
// 68 Access + Project appContext = 1000100
// 69 Access + Project + Excel appContext = 1000101
// 70 Access + Project + Word appContext = 1000110
// 71 Access + Project + Word + Excel appContext = 1000111
// 80 Access + PowerPoint appContext = 1010000
// 81 Access + PowerPoint + Excel appContext = 1010001
// 82 Access + PowerPoint + Word appContext = 1010010
// 83 Access + PowerPoint + Word + Excel appContext = 1010011
// 84 Access + PowerPoint + Project appContext = 1010100
// 85 Access + PowerPoint + Project + Excel appContext = 1010101
// 86 Access + PowerPoint + Project + Word appContext = 1010110
// 87 Access + PowerPoint + Project + Word + Excel appContext = 1010111
